server:
  port: 7080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: "/"
      path-mapping:
        prometheus: metrics
        health: quartz/v1/health

spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

mysqlConfig:
  acquireIncrement: 2
  driverClass: com.mysql.jdbc.Driver
  idleConnectionTestPeriodInSeconds: 100
  idleMaxAgeInSeconds: 100
  jdbcUrl: "jdbc:mysql://localhost:3306/quartz?useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true&&useSSL=false&zeroDateTimeBehavior=convertToNull"
  maxConnectionsPerPartition: 10
  minConnectionsPerPartition: 10
  partitionCount: 2
  password: root
  statementsCacheSize: 10
  user: root
####### SPRING JPA ############

servicesConfig:
  services:
    athena:
      topic: "scheduler"
      target:
        - notify-session-start
        - session-validate
        - session-daily
        - session-terminate
        - auto-close-lsg
        - insert-timeseries-data

externalServicesConfig:
  services:
    noongate:
      host: "http://localhost"
      port: "8090"
      apis:
        noongateInjest:
          method: GET
          endpoint: "/athena/v1/"
          connectionTimeout: 1000
          socketTimeout: 1000
          connectionRequestTimeout: 1000